<?php
$cv=$cv??[];$templates=$templates??['classic','minimal','modern'];$id=$cv['id']??($cv['cv_id']??($_GET['id']??''));
$h=fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');
$name=$cv['full_name']??($cv['name']??'Your CV');$category=$cv['category_name']??'Online CV';
$cards=[
 'classic'=>['title'=>'Classic','desc'=>'Trang trọng, phù hợp resume truyền thống và môi trường doanh nghiệp.','class'=>'classic'],
 'minimal'=>['title'=>'Minimal','desc'=>'Tối giản, nhiều khoảng trắng, tập trung vào nội dung chính.','class'=>'minimal'],
 'modern'=>['title'=>'Modern','desc'=>'Hiện đại, nổi bật, có sidebar và gradient chuyên nghiệp.','class'=>'modern'],
];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Choose CV Template</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:linear-gradient(135deg,#eef4ff,#f8fafc);color:#0f172a}.wrap{width:min(1120px,calc(100% - 32px));margin:40px auto}.hero{background:linear-gradient(135deg,#0f172a,#2563eb 62%,#06b6d4);color:#fff;border-radius:30px;padding:42px;box-shadow:0 24px 70px rgba(37,99,235,.22)}h1{font-size:clamp(34px,5vw,58px);margin:0;letter-spacing:-1.8px}.hero p{color:rgba(255,255,255,.84);line-height:1.7}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin-top:26px}.card{background:#fff;border:1px solid #dbe4f0;border-radius:28px;overflow:hidden;box-shadow:0 20px 50px rgba(15,23,42,.10)}.preview{height:220px;padding:22px}.classic .preview{background:#fbf7f2;font-family:Georgia,serif}.minimal .preview{background:#fff}.modern .preview{background:linear-gradient(135deg,#312e81,#06b6d4);color:#fff}.fake-name{font-size:28px;font-weight:900;letter-spacing:-1px;margin-bottom:10px}.classic .fake-name{text-transform:uppercase;letter-spacing:1px;border-bottom:3px double #d6c7b8;padding-bottom:12px}.line{height:9px;border-radius:999px;background:currentColor;opacity:.18;margin:12px 0}.line.short{width:62%}.content{padding:24px}.content h2{margin:0 0 8px}.content p{color:#64748b;line-height:1.6;min-height:74px}.btns{display:flex;gap:10px}.btn{flex:1;text-align:center;text-decoration:none;border-radius:16px;padding:12px 14px;font-weight:900}.view{background:#2563eb;color:#fff}.edit{background:#e2e8f0;color:#0f172a}.top-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px}.top-actions a{color:#fff;text-decoration:none;border:1px solid rgba(255,255,255,.3);border-radius:999px;padding:10px 15px;font-weight:800;background:rgba(255,255,255,.14)}@media(max-width:900px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><section class="hero"><h1>Choose CV Template</h1><p><strong><?= $h($name) ?></strong> · <?= $h($category) ?><br>Ba template bên dưới dùng cùng một dữ liệu CV đã lưu trong database, chỉ khác layout và visual style.</p><div class="top-actions"><a href="?route=seeker/cv/edit">Edit CV</a></div></section><div class="grid"><?php foreach($cards as $key=>$card):?><article class="card <?= $h($card['class']) ?>"><div class="preview"><div class="fake-name"><?= $h($name) ?></div><div class="line"></div><div class="line short"></div><div class="line"></div><div class="line short"></div></div><div class="content"><h2><?= $h($card['title']) ?></h2><p><?= $h($card['desc']) ?></p><div class="btns"><a class="btn view" href="?route=seeker/cv/view<?= $id?'&id='.$h($id):'' ?>&template=<?= $h($key) ?>">View</a><a class="btn edit" href="?route=seeker/cv/edit">Edit</a></div></div></article><?php endforeach;?></div></div></body></html>
